version: "1"
rules:
  - base: master
    upstream: LmeSzinc:master
    mergeMethod: squash
    mergeUnstable: false
  - base: dev
    upstream: master
    assignees:
      - LinnicoXin
    reviewers:
      - LinnicoXin
    conflictReviewers:
      - LinnicoXin
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"
