version: "1"
rules:
  - base: master
    upstream: LmeSzinc:master    # change `wei` to the owner of upstream repo
    mergeMethod: none
    mergeUnstable: false
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"
